### ISSUE TITLE
SkypeOnlineConnector is not downloadable from the PowerShell Gallery

### ISSUE THREAD

**Issue by thomasvochten** [martensnico/Office365.Connect#5]
I could not find the SkypeOnlineConnector module through the PowerShell Gallery, although the module suggests this should be possible. Automatically installing it therefore fails too. Probably need to include a download link, link the Microsoft Online Services Sign-in Assistant

**Comment by kilasuit** [comment]
@martensnico - this could be replaced with using an Invoke-WebRequest to the url for the Skype Online Connector Module and use `-OutFile` and then `Start-Process to the path` to install it 

Something similar to https://github.com/kilasuit/PoshFunctions/blob/Dev/Scripts/Install-Win10RSATTools.ps1

**Comment by martensnico** [comment]
I'm working on making automatic install of the Skype module and the sign-in assistant optional. So people can decide. Thanks!

**Comment by martensnico** [comment]
You now have the choice to automatically download and install:
- Microsoft Online Services Sign-in Assistant for IT Professionals RTW 
- Skype for Business Online PowerShell module
