### ISSUE TITLE
Use after choosing fix

### ISSUE THREAD

**Issue by NealBongers** [martensnico/Office365.Connect#7]
Now when using, after running the menu, you need to press q to quit the menu.
Instead t might be better to quit automatically after the menu

Change
`switch ($userInput.key)
			{
				q { $continue = $false }
				c { ResetSteps($steps) }
				Enter { RunSteps($steps) }
				default { SetStep $userInput.keyChar $steps }
			}`

To 
`switch ($userInput.key)
			{
				q { $continue = $false }
				c { ResetSteps($steps) }
				Enter { RunSteps($steps); $continue = $false }
				default { SetStep $userInput.keyChar $steps }
			}`

Or add it as an function to insert also some text stating you can use the full functions right away.

**Comment by martensnico** [comment]
Thanks, will look in to this today!
