### ISSUE TITLE
Add possibility to add credentials automatic to the Windows Vault

### ISSUE THREAD

**Issue by NealBongers** [martensnico/Office365.Connect#8]
There is a script which enables you to add the credentials automatic to the vault. Maybe nice for first time use, no need to put it there manually.

https://gallery.technet.microsoft.com/scriptcenter/How-to-add-credentials-to-c8e9bd5f

**Comment by NealBongers** [comment]
Edited function, ready for use:

`Function Add-OSCCredential
{
	$target = Read-Host "Internet or network address"
	$userName = Read-Host "UserName"
	$Password = Read-Host "Password" -AsSecureString
	If($target -and $userName)
	{
		If($Password)
		{
			[string]$result = cmdkey /generic:$target /user:$userName /pass:$Password
		}
		Else
		{
			[string]$result = cmdkey /generic:$target /user:$userName 
		}
		If($result -match "The command line parameters are incorrect")
		{
			Write-Error "Failed to add Windows Credential to Windows vault."
		}
		ElseIf($result -match "CMDKEY: Credential added successfully")
		{
			Write-Host "Credential added successfully."
		}
	}
	Else
	{
		Write-Error "Internet(network address) or username can not be empty,please try again."
		Add-OSCCredential
	}
	
}

Add-OSCCredential`

**Comment by kilasuit** [comment]
Potential to use https://github.com/jaykul/bettercredentials for this (which is what I use in my scripts)

**Comment by martensnico** [comment]
I added the functionality (didn't see yours in time Ryan, so used the New-StoredCredential cmdlet from the CredentialManager Module). Have to see if we can promote this someway, now it just asks to create a new credential if it doesn't exist yet. Any ideas ? :)
